name: dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'TweetBaseName'
        required: true

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.cmd SendTweet'
        run: ./build.cmd SendTweet
        env:
            GitHubToken: ${{ secrets.GITHUB_TOKEN }}
            TwitterConsumerKey: ${{ secrets.TWITTER_CONSUMER_KEY }}
            TwitterConsumerSecret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
            TwitterAccessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            TwitterAccessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
